name: Build Android and iOS
on:
  push:
    branches:
      - release
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test

  build-android:
      #needs: install-and-test
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            npm install
        - name: Graddle fix (for permission denied error)
          run: |
            cd android && chmod +x gradlew
        - name: Build Android Release
          run: |
            cd android && ./gradlew assembleRelease
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: app-release.apk
            path: android/app/build/outputs/apk/release/
            
  build-ios:
      #needs: install-and-test
      runs-on: macos
      steps: 
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            npm install
        - name: Install pod dependencies
          run: |
            cd ios && pod install
        - name: Build app
          run: |       
            xcodebuild -workspace pokedex.xcworkspace -scheme pokedex archive -archivePath pokedex.xcarchive -allowProvisioningUpdates
            xcodebuild -exportArchive -archivePath ./pokedex.xcarchive -exportPath . -exportOptionsPlist pokedex/Info.plist
            mv pokedex.ipa ../pokedex.ipa
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: myapp.ipa
            path: ios/build/
