name: Build Android and iOS
on:
  push:
    branches:
      - release
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test

  build-android:
    #needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Graddle fix (for permission denied error)
        run: |
          cd android && chmod +x gradlew
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/

  build-ios:
    #needs: install-and-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build ios
        uses: yukiarrr/ios-build-action@v1.3.2
        with:
          project-path: ios/pokedex.xcodeproj
          workspace-path: ios/pokedex.xcworkspace
          output-path: output/output.ipa
          scheme: pokedex
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: output/output.ipa
