name: Build Android and iOS
on:
  push:
    branches:
      - main
      - release
      - 'release/**'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason (optional)'
        required: false
        default: 'Manual'
        
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test

  build-android:
    #needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Graddle fix (for permission denied error)
        run: |
          cd android && chmod +x gradlew
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/

  build-ios:
    #needs: install-and-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |
          cd ios && xcodebuild -workspace pokedex.xcworkspace -scheme pokedex archive -archivePath pokedex.xcarchive -allowProvisioningUpdates -UseModernBuildSystem=NO
          cd ios && xcodebuild -exportArchive -archivePath ./pokedex.xcarchive -exportPath . -exportOptionsPlist pokedex/Info.plist
          mv pokedex.ipa ../pokedex.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: pokedex.ipa
          path: ios/build/
